- name: Clean up {{ code_server_dir }}
  become: yes
  file:
    state: absent
    path: "{{ code_server_dir }}"

- name: Create {{ code_server_dir }}
  become: yes
  file:
    state: directory
    path: "{{ code_server_dir }}"

- name: Download code-server v3
  become: yes
  unarchive:
    remote_src: yes
    src: "{{ code_server_tar_url }}"
    dest: "{{ code_server_dir }}"
    extra_opts:
      - --strip-components=1
  notify: Restart code-server
  # Note that code-server release tag has a 'v' prefix since v3.3.0,
  # while `code-server --version` never outputs the 'v' prefix.
  when: not code_server_exists.stat.exists or
        code_server_version.stdout != code_server_cleaned_ver

- name: Add {{ code_server_bin_dir }}/code-server
  become: yes
  file:
    state: link
    src: "{{ code_server_dir }}{{ '/bin' if code_server_cleaned_ver is version('3.3.0', '>=') else '' }}/code-server"
    dest: "{{ code_server_bin_dir }}/code-server"
    # force is required if upgrade from v1 or v2,
    # in which case dest exists and is a file.
    force: yes
  notify: Restart code-server
