---
- name: Test connectivity locally
  wait_for:
    port: "{{ code_server_port }}"
    timeout: 10
  when: code_server_user == "root"

- name: Test connectivity locally
  wait_for:
    port: "{{ code_server_user_port }}"
    timeout: 10
  when: code_server_user != "root"
